Repository DailyBotHQ/search-text-highlight, pull requests merged in 2023-07, with the labels that each got.

#47 Improving workflows and adding new ones
  .github/workflows/check_and_merge_packages_upgrades_pr.yml
  .github/workflows/check_packages_versions.yml
  .github/workflows/code_check.yml
  .github/workflows/pull_request_check.yml
  .github/workflows/release_and_publish.yml
  README.md
Labels: Size - L

#48 Upgrading docker version
  .github/workflows/pull_request_check.yml
  docker/local/searchTextHL/Dockerfile
Labels: Size - XS

#49 Upgrading docker version
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#50 Upgrading docker version
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#51 Upgrading packages versions
  .github/scripts/get_github_release_log.sh
  .github/scripts/get_packages_upgrades.sh
  .prettierrc
  docker/custom_commands.sh
  package-lock.json
  package.json
Labels: Size - XXL

#52 Fixing workflows scripts
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#53 Fixing workflows scripts
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#54 Fixing workflows scripts
  .github/workflows/release_and_publish.yml
Labels: Size - S

#55 Fixing workflows scripts
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#56 Improving workflows
  .github/workflows/check_and_merge_packages_upgrades_pr.yml
  .github/workflows/check_branches_state.yml
  .github/workflows/check_packages_versions.yml
  .github/workflows/release_and_publish.yml
Labels: Size - S

#57 Improving workflows
  .github/workflows/check_branches_state.yml
  .github/workflows/pull_request_check.yml
Labels: Size - XS

#59 Updating notification channels vars
  .github/workflows/check_and_merge_packages_upgrades_pr.yml
  .github/workflows/check_branches_state.yml
  .github/workflows/check_packages_versions.yml
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#60 🤖 Upgrading packages versions
  package-lock.json
  package.json
Labels: Size - M
