Repository DailyBotHQ/search-text-highlight, pull requests merged in 2024-08, with the labels that each got.

#96 🤖 Upgrading packages versions
  package-lock.json
  package.json
Labels: Size - XXL

#97 🤖 Upgrading packages versions
  package-lock.json
  package.json
Labels: Size - M

#98 Upgrading packages and updating github actions
  .github/workflows/check_and_merge_packages_upgrades_pr.yml
  .github/workflows/check_packages_versions.yml
  .github/workflows/code_check.yml
  .github/workflows/release_and_publish.yml
  docker/local/searchTextHL/Dockerfile
  package-lock.json
  package.json
Labels: Size - XL

#99 🤖 Upgrading packages versions
  package-lock.json
  package.json
Labels: Size - M
